# Generated by Django 4.2.2 on 2025-02-14 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=150, verbose_name='улица')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='номер дома')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'контакты сети',
                'verbose_name_plural': 'контакты сетей',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='наименование')),
                ('debt', models.FloatField(default=0.0, verbose_name='задолженность перед поставщиком')),
                ('creation_time', models.DateField(auto_now=True, verbose_name='дата создания')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_contacts', to='electronics.contact', verbose_name='контакты')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_supplier', to='electronics.network', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'сеть',
                'verbose_name_plural': 'сети',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='наименование')),
                ('model', models.CharField(max_length=200, verbose_name='модель')),
                ('launch_date', models.DateField(verbose_name='дата выхода на рынок')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_network', to='electronics.network', verbose_name='сеть')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
